theme: jekyll-theme-minimal
title: ğŸ‘©ğŸ»â€ğŸ’» Cass's CV
subtitle: FrontEnd Developer
description: <a href="CassiaMelvinResume.pdf">Download PDF</a>|<a href="CassiaMelvinResume.pdf">HTML Version</a>
